# Generated by Django 5.1.1 on 2024-09-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_orderdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='stripe_payment_intent',
            field=models.CharField(max_length=500),
        ),
    ]
