# Generated by Django 5.1.1 on 2024-09-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_orderdetails_stripe_payment_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='checkout_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
