# Generated by Django 4.2 on 2024-08-17 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieModels',
            new_name='MovieData',
        ),
    ]
