# Generated by Django 4.2 on 2024-08-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_moviemodels_moviedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='category',
            field=models.CharField(default='Comedy', max_length=200),
        ),
    ]
