# Generated by Django 4.2 on 2024-08-17 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_moviedata_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviedata',
            old_name='category',
            new_name='gener',
        ),
    ]
