# Generated by Django 4.2 on 2024-08-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_category_moviedata_gener'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='gener',
            field=models.CharField(default='action', max_length=200),
        ),
    ]
