# Generated by Django 4.2 on 2024-08-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_moviedata_gener'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='Images/None/Noimg.jpg', upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='gener',
            field=models.CharField(default='Comedy', max_length=200),
        ),
    ]
