# Generated by Django 5.1 on 2024-08-21 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='sammury',
            new_name='summary',
        ),
    ]
