# Generated by Django 5.1 on 2024-09-06 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0002_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ('date',)},
        ),
    ]
