# Generated by Django 5.1 on 2024-08-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='fats',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='protein',
            field=models.FloatField(default=0),
        ),
    ]
