# Generated by Django 5.1 on 2024-08-30 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_linked_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='linked_by',
            new_name='liked_by',
        ),
    ]
