# Generated by Django 5.1 on 2024-09-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='gener',
            field=models.CharField(default='Comedy', max_length=100),
        ),
    ]
